export const siteConfig = {
  name: "Safety Sphere Solution",
  legalName: "Safety Sphere Solution",
  tagline: "360° Fire, EHS & Digital Safety Solutions",
  description:
    "Leading Fire Safety, Electrical & Fire Compliance Audits, EHS, Construction HSE, ESG, Physical Security & Life Safety, and Digital Safety consulting company in India. Fire NOC, thermography, training, and AI safety monitoring.",
  url: "https://safetyspheresolution.vercel.app",
  phone: "+91 77638 06992",
  email: "safetyspheresolution@gmail.com",
  whatsapp: "917763806992",
  locations: [
    { city: "Nagpur", state: "Maharashtra", short: "Nagpur (MH)" },
    { city: "Raipur", state: "Chhattisgarh", short: "Raipur (CG)" },
  ],
  keywords: [
    "Fire Safety Consultant India",
    "Fire Safety Compliance Audit",
    "Fire NOC Consultant",
    "Electrical Safety Audit India",
    "Thermography Audit",
    "Arc Flash Study",
    "EHS Consultant",
    "ESG Consultant",
    "Construction HSE Management",
    "Safety Audit Services",
    "Fire Protection Systems",
    "Fire Engineering Consultant",
    "Industrial Safety Training",
    "LOTO Implementation",
    "AI Safety Monitoring",
    "ISO 45001 Consultant",
    "Environmental Compliance",
    "Fire Alarm System",
    "Aspirating Smoke Detection",
    "Fire Hydrant System",
    "Fire Risk Assessment",
    "Physical Security Risk Assessment",
    "Safety Consultancy",
    "Digital Safety Solutions",
    "Occupational Health and Safety",
    "Industrial Fire Protection",
  ],
  social: {
    linkedin: "https://www.linkedin.com/",
    twitter: "https://twitter.com/",
  },
} as const;
