export const siteConfig = {
  name: "Safety Sphere Solution",
  legalName: "Safety Sphere Solution",
  tagline: "360° Fire, EHS & Digital Safety Solutions",
  description:
    "Leading Fire Safety, Environment, Health & Safety (EHS), ESG, Digital Safety, and Industrial Consulting company in India. Fire NOC, safety audits, training, and AI safety monitoring.",
  url: "https://safetyspheresolution.com",
  phone: "+91 77638 06992",
  email: "safetyspheresolution@gmail.com",
  whatsapp: "917763806992",
  locations: [
    { city: "Nagpur", state: "Maharashtra", short: "Nagpur (MH)" },
    { city: "Raipur", state: "Chhattisgarh", short: "Raipur (CG)" },
  ],
  keywords: [
    "Fire Safety Consultant India",
    "Fire NOC Consultant",
    "EHS Consultant",
    "ESG Consultant",
    "Safety Audit Services",
    "Fire Protection Systems",
    "Fire Engineering Consultant",
    "Industrial Safety Training",
    "LOTO Implementation",
    "AI Safety Monitoring",
    "ISO 45001 Consultant",
    "Environmental Compliance",
    "Fire Alarm System",
    "Fire Hydrant System",
    "Fire Risk Assessment",
    "Safety Consultancy",
    "Safety Management Software",
    "Digital Safety Solutions",
    "Occupational Health and Safety",
    "Industrial Fire Protection",
  ],
  social: {
    linkedin: "https://www.linkedin.com/",
    twitter: "https://twitter.com/",
  },
} as const;
